package com.laowang.datasource.beans;

public class Departments {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column departments.dept_no
     *
     * @mbggenerated
     */
    private String deptNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column departments.dept_name
     *
     * @mbggenerated
     */
    private String deptName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column departments.dept_no
     *
     * @return the value of departments.dept_no
     *
     * @mbggenerated
     */
    public String getDeptNo() {
        return deptNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column departments.dept_no
     *
     * @param deptNo the value for departments.dept_no
     *
     * @mbggenerated
     */
    public void setDeptNo(String deptNo) {
        this.deptNo = deptNo == null ? null : deptNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column departments.dept_name
     *
     * @return the value of departments.dept_name
     *
     * @mbggenerated
     */
    public String getDeptName() {
        return deptName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column departments.dept_name
     *
     * @param deptName the value for departments.dept_name
     *
     * @mbggenerated
     */
    public void setDeptName(String deptName) {
        this.deptName = deptName == null ? null : deptName.trim();
    }
}