package com.laowang.datasource.beans;

import java.util.Date;

public class DeptEmp extends DeptEmpKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dept_emp.from_date
     *
     * @mbggenerated
     */
    private Date fromDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dept_emp.to_date
     *
     * @mbggenerated
     */
    private Date toDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dept_emp.from_date
     *
     * @return the value of dept_emp.from_date
     *
     * @mbggenerated
     */
    public Date getFromDate() {
        return fromDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dept_emp.from_date
     *
     * @param fromDate the value for dept_emp.from_date
     *
     * @mbggenerated
     */
    public void setFromDate(Date fromDate) {
        this.fromDate = fromDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dept_emp.to_date
     *
     * @return the value of dept_emp.to_date
     *
     * @mbggenerated
     */
    public Date getToDate() {
        return toDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dept_emp.to_date
     *
     * @param toDate the value for dept_emp.to_date
     *
     * @mbggenerated
     */
    public void setToDate(Date toDate) {
        this.toDate = toDate;
    }
}