package com.laowang.datasource.beans;

public class DeptManagerKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dept_manager.emp_no
     *
     * @mbggenerated
     */
    private Integer empNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dept_manager.dept_no
     *
     * @mbggenerated
     */
    private String deptNo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dept_manager.emp_no
     *
     * @return the value of dept_manager.emp_no
     *
     * @mbggenerated
     */
    public Integer getEmpNo() {
        return empNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dept_manager.emp_no
     *
     * @param empNo the value for dept_manager.emp_no
     *
     * @mbggenerated
     */
    public void setEmpNo(Integer empNo) {
        this.empNo = empNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dept_manager.dept_no
     *
     * @return the value of dept_manager.dept_no
     *
     * @mbggenerated
     */
    public String getDeptNo() {
        return deptNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dept_manager.dept_no
     *
     * @param deptNo the value for dept_manager.dept_no
     *
     * @mbggenerated
     */
    public void setDeptNo(String deptNo) {
        this.deptNo = deptNo == null ? null : deptNo.trim();
    }
}