package com.laowang.datasource.beans;

import java.util.Date;

public class SalariesKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column salaries.emp_no
     *
     * @mbggenerated
     */
    private Integer empNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column salaries.from_date
     *
     * @mbggenerated
     */
    private Date fromDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column salaries.emp_no
     *
     * @return the value of salaries.emp_no
     *
     * @mbggenerated
     */
    public Integer getEmpNo() {
        return empNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column salaries.emp_no
     *
     * @param empNo the value for salaries.emp_no
     *
     * @mbggenerated
     */
    public void setEmpNo(Integer empNo) {
        this.empNo = empNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column salaries.from_date
     *
     * @return the value of salaries.from_date
     *
     * @mbggenerated
     */
    public Date getFromDate() {
        return fromDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column salaries.from_date
     *
     * @param fromDate the value for salaries.from_date
     *
     * @mbggenerated
     */
    public void setFromDate(Date fromDate) {
        this.fromDate = fromDate;
    }
}