package com.laowang.datasource.beans;

import java.util.Date;

public class Salaries extends SalariesKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column salaries.salary
     *
     * @mbggenerated
     */
    private Integer salary;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column salaries.to_date
     *
     * @mbggenerated
     */
    private Date toDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column salaries.salary
     *
     * @return the value of salaries.salary
     *
     * @mbggenerated
     */
    public Integer getSalary() {
        return salary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column salaries.salary
     *
     * @param salary the value for salaries.salary
     *
     * @mbggenerated
     */
    public void setSalary(Integer salary) {
        this.salary = salary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column salaries.to_date
     *
     * @return the value of salaries.to_date
     *
     * @mbggenerated
     */
    public Date getToDate() {
        return toDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column salaries.to_date
     *
     * @param toDate the value for salaries.to_date
     *
     * @mbggenerated
     */
    public void setToDate(Date toDate) {
        this.toDate = toDate;
    }
}