package com.laowang.datasource.beans;

import java.util.Date;

public class Titles extends TitlesKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column titles.to_date
     *
     * @mbggenerated
     */
    private Date toDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column titles.to_date
     *
     * @return the value of titles.to_date
     *
     * @mbggenerated
     */
    public Date getToDate() {
        return toDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column titles.to_date
     *
     * @param toDate the value for titles.to_date
     *
     * @mbggenerated
     */
    public void setToDate(Date toDate) {
        this.toDate = toDate;
    }
}