package com.laowang.datasource.beans;

import java.util.Date;

public class TitlesKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column titles.emp_no
     *
     * @mbggenerated
     */
    private Integer empNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column titles.title
     *
     * @mbggenerated
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column titles.from_date
     *
     * @mbggenerated
     */
    private Date fromDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column titles.emp_no
     *
     * @return the value of titles.emp_no
     *
     * @mbggenerated
     */
    public Integer getEmpNo() {
        return empNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column titles.emp_no
     *
     * @param empNo the value for titles.emp_no
     *
     * @mbggenerated
     */
    public void setEmpNo(Integer empNo) {
        this.empNo = empNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column titles.title
     *
     * @return the value of titles.title
     *
     * @mbggenerated
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column titles.title
     *
     * @param title the value for titles.title
     *
     * @mbggenerated
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column titles.from_date
     *
     * @return the value of titles.from_date
     *
     * @mbggenerated
     */
    public Date getFromDate() {
        return fromDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column titles.from_date
     *
     * @param fromDate the value for titles.from_date
     *
     * @mbggenerated
     */
    public void setFromDate(Date fromDate) {
        this.fromDate = fromDate;
    }
}